//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chroom
    {
        public chroom()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int id { get; set; }
        public Nullable<int> p1 { get; set; }
        public Nullable<int> p2 { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
