//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.FacilitiesForRooms = new HashSet<FacilitiesForRoom>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string icon { get; set; }
    
        public virtual ICollection<FacilitiesForRoom> FacilitiesForRooms { get; set; }
    }
}
