//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public Nullable<int> senderid { get; set; }
        public Nullable<int> recieverid { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string stat { get; set; }
        public Nullable<int> chroom { get; set; }
    
        public virtual chroom chroom1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
