//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentealseat
    {
        public Rentealseat()
        {
            this.rentrevs = new HashSet<rentrev>();
            this.Requests = new HashSet<Request>();
        }
    
        public int id { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public string pic { get; set; }
    
        public virtual ICollection<rentrev> rentrevs { get; set; }
        public virtual Room Room { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
