//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.reviewofrents = new HashSet<reviewofrent>();
        }
    
        public int id { get; set; }
        public string review1 { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<reviewofrent> reviewofrents { get; set; }
        public virtual Reviewofuser Reviewofuser { get; set; }
    }
}
