//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upazila
    {
        public int UpazilaId { get; set; }
        public int DistrictId { get; set; }
        public string UpazilaName { get; set; }
        public string bn_name { get; set; }
        public string url { get; set; }
    
        public virtual District District { get; set; }
    }
}
