//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.FacilitiesForRooms = new HashSet<FacilitiesForRoom>();
            this.Rentealseats = new HashSet<Rentealseat>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public Nullable<int> noofrooms { get; set; }
        public Nullable<int> maxmembers { get; set; }
        public Nullable<int> atfloor { get; set; }
        public Nullable<int> sqft { get; set; }
        public string zone { get; set; }
        public Nullable<int> upazilaid { get; set; }
        public Nullable<int> ownerid { get; set; }
        public string upname { get; set; }
    
        public virtual ICollection<FacilitiesForRoom> FacilitiesForRooms { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<Rentealseat> Rentealseats { get; set; }
    }
}
